<a href="https://colab.research.google.com/github/manasvisrivastava-25BAI/EDA-LAB/blob/main/eda_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df1 = pd.DataFrame({'Course_code': [101, 103, 105, 107, 109, 110, 130, 150],'Marks': [98,56,78,93,80,62,79,50]})
df2 = pd.DataFrame({'Course_code': [102,104,106,108,110,112,114,116], 'Marks':[76,43,79,89,97,94,68,88]})

In [6]:
#concatenation
dfconcat = pd.concat([df1, df2], ignore_index=True)

In [7]:

df2.merge(df1, how = 'left')

   Course_code  Marks
0          102     76
1          104     43
2          106     79
3          108     89
4          110     97
5          112     94
6          114     68
7          116     88

In [8]:
dfconcat2 = pd.concat([df1,df2], axis = 1)
print(dfconcat2)

   Course_code  Marks  Course_code  Marks
0          101     98          102     76
1          103     56          104     43
2          105     78          106     79
3          107     93          108     89
4          109     80          110     97
5          110     62          112     94
6          130     79          114     68
7          150     50          116     88

In [9]:
dfconcat.tail(5)

    Course_code  Marks
11          108     89
12          110     97
13          112     94
14          114     68
15          116     88

In [10]:
dfconcat.sort_values('Course_code')

    Course_code  Marks
0           101     98
8           102     76
1           103     56
9           104     43
2           105     78
10          106     79
3           107     93
11          108     89
4           109     80
12          110     97
5           110     62
13          112     94
14          114     68
15          116     88
6           130     79
7           150     50

In [11]:
dfconcat.head(6)

   Course_code  Marks
0          101     98
1          103     56
2          105     78
3          107     93
4          109     80
5          110     62

In [12]:
dfconcat2['Sum'] = df1['Marks'] + df2['Marks']
dfconcat2

   Course_code  Marks  Course_code  Marks  Sum
0          101     98          102     76  174
1          103     56          104     43   99
2          105     78          106     79  157
3          107     93          108     89  182
4          109     80          110     97  177
5          110     62          112     94  156
6          130     79          114     68  147
7          150     50          116     88  138

In [13]:
df1.describe()

       Course_code      Marks
count     8.000000   8.000000
mean    114.375000  74.500000
std      16.953192  17.138095
min     101.000000  50.000000
25%     104.500000  60.500000
50%     108.000000  78.500000
75%     115.000000  83.250000
max     150.000000  98.000000

In [14]:
import numpy as np

In [15]:
data = np.arange(20).reshape((5,4))
i = ['a', 'b', 'c', 'd', 'e']
df3 = pd.DataFrame(data, index = i, columns=[1,2,3,4])
df3

    1   2   3   4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19

In [16]:
df3.stack()

a  1     0
   2     1
   3     2
   4     3
b  1     4
   2     5
   3     6
   4     7
c  1     8
   2     9
   3    10
   4    11
d  1    12
   2    13
   3    14
   4    15
e  1    16
   2    17
   3    18
   4    19
dtype: int64