<a href="https://colab.research.google.com/github/manasvisrivastava-25BAI/EDA-LAB/blob/main/exp4_28.07.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [142]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer

In [143]:
data = np.arange(15,30).reshape(5,3)
dfx = pd.DataFrame(data, index = ['guitar', 'piano', 'flute', 'violin', 'drums'], columns = ['store1', 'store2', 'store3'])
dfx

        store1  store2  store3
guitar      15      16      17
piano       18      19      20
flute       21      22      23
violin      24      25      26
drums       27      28      29

In [144]:
dfx['store4'] = np.nan
dfx.loc['bass'] = np.arange(15,19)
dfx.loc['saxophone'] = np.nan
dfx['store5'] = np.nan
dfx['store4']['guitar'] = 20
dfx

/tmp/ipykernel_1690/2559069044.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['store4']['guitar'] = 20

           store1  store2  store3  store4  store5
guitar       15.0    16.0    17.0    20.0     NaN
piano        18.0    19.0    20.0     NaN     NaN
flute        21.0    22.0    23.0     NaN     NaN
violin       24.0    25.0    26.0     NaN     NaN
drums        27.0    28.0    29.0     NaN     NaN
bass         15.0    16.0    17.0    18.0     NaN
saxophone     NaN     NaN     NaN     NaN     NaN

In [145]:
dfx.isnull()

           store1  store2  store3  store4  store5
guitar      False   False   False   False    True
piano       False   False   False    True    True
flute       False   False   False    True    True
violin      False   False   False    True    True
drums       False   False   False    True    True
bass        False   False   False   False    True
saxophone    True    True    True    True    True

In [146]:
dfx.notnull()

           store1  store2  store3  store4  store5
guitar       True    True    True    True   False
piano        True    True    True   False   False
flute        True    True    True   False   False
violin       True    True    True   False   False
drums        True    True    True   False   False
bass         True    True    True    True   False
saxophone   False   False   False   False   False

In [147]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

In [148]:
dfx.isnull().sum().sum()

np.int64(15)

In [149]:
dfx.count()

store1    6
store2    6
store3    6
store4    2
store5    0
dtype: int64

In [150]:
dfx.store4[dfx.store4.notnull()]

guitar    20.0
bass      18.0
Name: store4, dtype: float64

In [151]:
dfx.store4.dropna()

guitar    20.0
bass      18.0
Name: store4, dtype: float64

In [152]:
dfx.dropna()

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

In [153]:
dfx.dropna(how = 'all')

        store1  store2  store3  store4  store5
guitar    15.0    16.0    17.0    20.0     NaN
piano     18.0    19.0    20.0     NaN     NaN
flute     21.0    22.0    23.0     NaN     NaN
violin    24.0    25.0    26.0     NaN     NaN
drums     27.0    28.0    29.0     NaN     NaN
bass      15.0    16.0    17.0    18.0     NaN

In [154]:
dfx.dropna(how = 'all', axis = 1)

           store1  store2  store3  store4
guitar       15.0    16.0    17.0    20.0
piano        18.0    19.0    20.0     NaN
flute        21.0    22.0    23.0     NaN
violin       24.0    25.0    26.0     NaN
drums        27.0    28.0    29.0     NaN
bass         15.0    16.0    17.0    18.0
saxophone     NaN     NaN     NaN     NaN

In [155]:
dfx.dropna(thresh = 5, axis = 1)

           store1  store2  store3
guitar       15.0    16.0    17.0
piano        18.0    19.0    20.0
flute        21.0    22.0    23.0
violin       24.0    25.0    26.0
drums        27.0    28.0    29.0
bass         15.0    16.0    17.0
saxophone     NaN     NaN     NaN

In [156]:
ar1 = np.array([100,200,np.nan,300])
ser1 = pd.Series(ar1)
print(ar1.mean())
print(ser1.mean())

nan
200.0

In [157]:
ser2 = dfx.store4
ser2.sum()

np.float64(38.0)

In [158]:
ser2.cumsum()

guitar       20.0
piano         NaN
flute         NaN
violin        NaN
drums         NaN
bass         38.0
saxophone     NaN
Name: store4, dtype: float64

In [159]:
filledDf = dfx.fillna(0)
filledDf

           store1  store2  store3  store4  store5
guitar       15.0    16.0    17.0    20.0     0.0
piano        18.0    19.0    20.0     0.0     0.0
flute        21.0    22.0    23.0     0.0     0.0
violin       24.0    25.0    26.0     0.0     0.0
drums        27.0    28.0    29.0     0.0     0.0
bass         15.0    16.0    17.0    18.0     0.0
saxophone     0.0     0.0     0.0     0.0     0.0

In [160]:
dfx.store4.fillna(method = 'ffill')

/tmp/ipykernel_1690/1942984426.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method = 'ffill')

guitar       20.0
piano        20.0
flute        20.0
violin       20.0
drums        20.0
bass         18.0
saxophone    18.0
Name: store4, dtype: float64

In [161]:
dfx.store4.fillna(method = 'bfill')

/tmp/ipykernel_1690/2312776902.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method = 'bfill')

guitar       20.0
piano        18.0
flute        18.0
violin       18.0
drums        18.0
bass         18.0
saxophone     NaN
Name: store4, dtype: float64

In [162]:
df = pd.DataFrame({
    "Age" : [25, np.nan, 30, 45, 50, 35, 40, 55],
    "Gender" : ['M', 'F', 'F', np.nan, 'M', 'M', 'F', 'F'],
    "Income" : [20000, 35000, 50000, 42000, 38000, 55000, np.nan, 60000]
})
df

    Age Gender   Income
0  25.0      M  20000.0
1   NaN      F  35000.0
2  30.0      F  50000.0
3  45.0    NaN  42000.0
4  50.0      M  38000.0
5  35.0      M  55000.0
6  40.0      F      NaN
7  55.0      F  60000.0

In [163]:
mean_imputer = SimpleImputer(strategy='mean')
df["Age_mean"] = mean_imputer.fit_transform(df[["Age"]])
df

    Age Gender   Income  Age_mean
0  25.0      M  20000.0      25.0
1   NaN      F  35000.0      40.0
2  30.0      F  50000.0      30.0
3  45.0    NaN  42000.0      45.0
4  50.0      M  38000.0      50.0
5  35.0      M  55000.0      35.0
6  40.0      F      NaN      40.0
7  55.0      F  60000.0      55.0

In [164]:
median_imputer = SimpleImputer(strategy="median")
df["Income_Median"] = median_imputer.fit_transform(df[["Income"]])
df

    Age Gender   Income  Age_mean  Income_Median
0  25.0      M  20000.0      25.0        20000.0
1   NaN      F  35000.0      40.0        35000.0
2  30.0      F  50000.0      30.0        50000.0
3  45.0    NaN  42000.0      45.0        42000.0
4  50.0      M  38000.0      50.0        38000.0
5  35.0      M  55000.0      35.0        55000.0
6  40.0      F      NaN      40.0        42000.0
7  55.0      F  60000.0      55.0        60000.0

In [165]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df["Gender_mode"] = mode_imputer.fit_transform(df[["Gender"]]).ravaaaaaaaaaaaaael()
df

    Age Gender   Income  Age_mean  Income_Median Gender_mode
0  25.0      M  20000.0      25.0        20000.0           M
1   NaN      F  35000.0      40.0        35000.0           F
2  30.0      F  50000.0      30.0        50000.0           F
3  45.0    NaN  42000.0      45.0        42000.0           F
4  50.0      M  38000.0      50.0        38000.0           M
5  35.0      M  55000.0      35.0        55000.0           M
6  40.0      F      NaN      40.0        42000.0           F
7  55.0      F  60000.0      55.0        60000.0           F

In [166]:
num_col = ["Age", "Income"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_col].copy()
df_mice.iloc[:,:] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Income_MICE"] = df_mice["Income"]
df

,Age,Gender,Income,Age_mean,Income_Median,Gender_mode,Age_MICE,Income_MICE
0,25.0,M,20000.0,25.0,20000.0,M,25.000000,20000.000000
1,NaN,F,35000.0,40.0,35000.0,F,36.506893,35000.000000
2,30.0,F,50000.0,30.0,50000.0,F,30.000000,50000.000000
3,45.0,NaN,42000.0,45.0,42000.0,F,45.000000,42000.000000
4,50.0,M,38000.0,50.0,38000.0,M,50.000000,38000.000000
5,35.0,M,55000.0,35.0,55000.0,M,35.000000,55000.000000
6,40.0,F,NaN,40.0,42000.0,F,40.000000,43012.768988
7,55.0,F,60000.0,55.0,60000.0,F,55.000000,60000.000000